#!/usr/bin/env bash

fin start

fin drush site-install -y \
  --account-pass=admin \
  --site-name='Drupal Tailwind CSS'

# Change the default theme
fin drush theme:enable tailwindcss -y
fin drush config-set system.theme default tailwindcss -y

fin drush uli -l http://drupal-tailwind.docksal
